name: Create Upload Keystore

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Create keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore my-upload-key.jks \
            -alias upload \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass 'ApsTool@2001' \
            -keypass 'ApsTool@2001' \
            -dname "CN=APS TOOLS, OU=A28 Technologies, O=A28 Technologies, L=India, ST=Karnataka, C=IN"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: aps-upload-keystore
          path: my-upload-key.jks
          retention-days: 1
